[tasks.dev]
run = 'watchexec -e .purs,.js -i output spago bundle --platform browser --bundle-type app'

[tasks.build]
run = 'spago bundle --platform browser --bundle-type app --minify'

[tasks.docs]
run = 'spago docs'

[tasks.clean]
run = 'rm -rf output index.js'

[env]
_.path = './node_modules/.bin'

[tools]
node = "22.20.0"
pitchfork = "latest"

# vim: ts=2 sts=2 sw=2 et
